export const EXPENSE_CATEGORIES = [
  'Food',
  'Transport',
  'Entertainment',
  'Utilities',
  'Shopping',
  'Healthcare',
  'Education',
  'Personal',
  'Travel',
  'Meals & Lodging',
  'Office Supplies',
  'Client Meetings',
  'Professional Development',
  'Other',
]
